Repository ec-europa/joinup-dev, pull requests merged in 2020-05, with the labels that each got.

#2084 ISAICP-5374: Bundle specific classes
  composer.json
  composer.lock
  config/sync/core.extension.yml
  web/modules/custom/joinup_bundle_class/joinup_bundle_class.info.yml
  web/modules/custom/joinup_bundle_class/src/JoinupBundleClassFieldAccessTrait.php
  web/modules/custom/joinup_event/joinup_event.info.yml
  web/modules/custom/joinup_event/joinup_event.module
  web/modules/custom/joinup_event/src/Entity/Event.php
  web/modules/custom/joinup_event/src/Entity/EventInterface.php
  web/modules/custom/joinup_event/src/Plugin/Validation/Constraint/EventLocationConstraintValidator.php
Labels: blocker, enhancement, ready for QA

#2110 ISAICP-5664: Contact form disclaimer message.
  tests/features/contact_form/submit_contact_form.feature
  web/modules/custom/contact_form/contact_form.module
Labels: ready for UAT

#2090 Isaicp-5690: Short ID field for collections and solutions.
  composer.json
  composer.lock
  config/sync/core.entity_form_display.rdf_entity.collection.default.yml
  config/sync/core.entity_form_display.rdf_entity.collection.propose.yml
  config/sync/core.entity_form_display.rdf_entity.solution.default.yml
  config/sync/core.entity_view_display.rdf_entity.collection.about.yml
  config/sync/core.entity_view_display.rdf_entity.collection.compact.yml
  config/sync/core.entity_view_display.rdf_entity.collection.default.yml
  config/sync/core.entity_view_display.rdf_entity.collection.digest_message_header.yml
  config/sync/core.entity_view_display.rdf_entity.collection.rdf_draft.yml
  config/sync/core.entity_view_display.rdf_entity.collection.view_mode_featured.yml
  config/sync/core.entity_view_display.rdf_entity.collection.view_mode_tile.yml
  config/sync/core.entity_view_display.rdf_entity.solution.about.yml
  config/sync/core.entity_view_display.rdf_entity.solution.default.yml
  config/sync/core.entity_view_display.rdf_entity.solution.group_header.yml
  config/sync/core.entity_view_display.rdf_entity.solution.rdf_draft.yml
  config/sync/core.entity_view_display.rdf_entity.solution.view_mode_featured.yml
  config/sync/core.entity_view_display.rdf_entity.solution.view_mode_tile.yml
  config/sync/field.field.rdf_entity.collection.field_short_id.yml
  config/sync/field.field.rdf_entity.solution.field_short_id.yml
  config/sync/field.storage.rdf_entity.field_short_id.yml
  config/sync/user.role.moderator.yml
  tests/features/joinup_group/short_id.feature
  web/modules/custom/asset_release/tests/src/Kernel/SyncFieldsFromParentSolutionTest.php
  web/modules/custom/collection/collection.behat.inc
  web/modules/custom/collection/collection.info.yml
  web/modules/custom/collection/config/install/core.entity_view_display.rdf_entity.collection.about.yml
  web/modules/custom/collection/config/optional/core.entity_form_display.rdf_entity.collection.default.yml
  web/modules/custom/collection/config/optional/core.entity_view_display.rdf_entity.collection.about.yml
  web/modules/custom/collection/config/optional/core.entity_view_display.rdf_entity.collection.compact.yml
  web/modules/custom/collection/config/optional/core.entity_view_display.rdf_entity.collection.default.yml
  web/modules/custom/collection/config/optional/core.entity_view_display.rdf_entity.collection.group_header.yml
  web/modules/custom/collection/config/optional/core.entity_view_display.rdf_entity.collection.rdf_draft.yml
  web/modules/custom/collection/config/optional/core.entity_view_display.rdf_entity.collection.view_mode_featured.yml
  web/modules/custom/collection/config/optional/core.entity_view_display.rdf_entity.collection.view_mode_tile.yml
  web/modules/custom/collection/config/optional/field.field.rdf_entity.collection.field_short_id.yml
  web/modules/custom/joinup_group/config/optional/views.view.members_overview.yml
  web/modules/custom/joinup_group/joinup_group.info.yml
  web/modules/custom/joinup_group/joinup_group.module
  web/modules/custom/joinup_group/joinup_group.permissions.yml
  web/modules/custom/joinup_group/src/Plugin/Validation/Constraint/UniqueShortIdInsensitiveConstraint.php
  web/modules/custom/joinup_group/src/Plugin/Validation/Constraint/UniqueShortIdInsensitiveValidator.php
  web/modules/custom/joinup_group/tests/src/ExistingSite/ShortIdAllowedValuesTest.php
  web/modules/custom/joinup_rdf/config/install/field.storage.rdf_entity.field_short_id.yml
  web/modules/custom/joinup_rdf/joinup_rdf.info.yml
  web/modules/custom/joinup_user/config/install/user.role.moderator.yml
  web/modules/custom/solution/config/optional/core.entity_view_display.rdf_entity.solution.about.yml
  web/modules/custom/solution/config/optional/core.entity_view_display.rdf_entity.solution.default.yml
  web/modules/custom/solution/config/optional/core.entity_view_display.rdf_entity.solution.group_header.yml
  web/modules/custom/solution/config/optional/core.entity_view_display.rdf_entity.solution.rdf_draft.yml
  web/modules/custom/solution/config/optional/core.entity_view_display.rdf_entity.solution.view_mode_featured.yml
  web/modules/custom/solution/config/optional/core.entity_view_display.rdf_entity.solution.view_mode_tile.yml
  web/modules/custom/solution/config/optional/field.field.rdf_entity.solution.field_short_id.yml
  web/modules/custom/solution/solution.behat.inc
  web/modules/custom/solution/solution.info.yml
Labels: ready for UAT

#2122 ISAICP-5973: Fix entity with double changed time
  web/modules/custom/joinup_core/joinup_core.post_update.php
Labels: ready for QA

#2103 ISAICP-5967: Convert the group administration report for both collections and solutions
  tests/behat-group-a-cphp.yml.dist
  tests/behat-group-b-cphp.yml.dist
  tests/behat-only-selenium-cphp.yml.dist
  tests/behat-remainder-cphp.yml.dist
  tests/behat.yml.dist
  tests/features/authentication.feature
  tests/features/joinup_core/reporting.feature
  tests/features/moderator/group_administrators_report.feature
  web/profiles/joinup/joinup.links.menu.yml
  web/profiles/joinup/joinup.routing.yml
  web/profiles/joinup/src/Controller/GroupAdministratorsController.php
  web/profiles/joinup/src/Form/ExportGroupAdministratorsForm.php
Labels: ready for UAT

#2108 ISAICP-5748: Provide a post update to fix the update date.
  web/modules/custom/joinup_core/joinup_core.post_update.php
Labels: ready for QA

#2125 ISAICP-5914: Remove old (post)updates
  README.md
  phpcs-ruleset.xml.dist
  phpstan.neon
  src/CodingStandards/Sniffs/NamingConventions/ValidUpdateNameSniff.php
  web/modules/custom/adms_validator/adms_validator.post_update.php
  web/modules/custom/asset_distribution/asset_distribution.install
  web/modules/custom/collection/collection.install
  web/modules/custom/collection/collection.post_update.php
  web/modules/custom/contact_form/contact_form.install
  web/modules/custom/contact_form/contact_form.post_update.php
  web/modules/custom/contact_information/contact_information.post_update.php
  web/modules/custom/custom_page/custom_page.post_update.php
  web/modules/custom/joinup_communities/eupl/eupl.post_update.php
  web/modules/custom/joinup_communities/spain_ctt/spain_ctt.post_update.php
  web/modules/custom/joinup_communities/tallinn/tallinn.install
  web/modules/custom/joinup_communities/tallinn/tallinn.post_update.php
  web/modules/custom/joinup_core/joinup_core.install
  web/modules/custom/joinup_core/joinup_core.post_update.php
  web/modules/custom/joinup_discussion/joinup_discussion.post_update.php
  web/modules/custom/joinup_eulogin/joinup_eulogin.post_update.php
  web/modules/custom/joinup_event/joinup_event.post_update.php
  web/modules/custom/joinup_front_page/joinup_front_page.post_update.php
  web/modules/custom/joinup_group/joinup_group.post_update.php
  web/modules/custom/joinup_invite/joinup_invite.post_update.php
  web/modules/custom/joinup_licence/joinup_licence.install
  web/modules/custom/joinup_licence/joinup_licence.post_update.php
  web/modules/custom/joinup_newsletter/joinup_newsletter.post_update.php
  web/modules/custom/joinup_sparql/joinup_sparql.post_update.php
  web/modules/custom/joinup_subscription/joinup_subscription.install
  web/modules/custom/joinup_subscription/joinup_subscription.post_update.php
  web/modules/custom/joinup_user/joinup_user.post_update.php
  web/modules/custom/joinup_video/joinup_video.post_update.php
  web/modules/custom/owner/owner.install
  web/modules/custom/solution/solution.post_update.php
  web/profiles/joinup/joinup.post_update.php
Labels: ready for QA

#2095 ISAICP-5876: Move custom page body to paragraphs.
  composer.json
  composer.lock
  config/sync/core.entity_form_display.node.custom_page.default.yml
  config/sync/core.entity_form_display.paragraph.simple_paragraph.default.yml
  config/sync/core.entity_view_display.node.custom_page.default.yml
  config/sync/core.entity_view_display.node.custom_page.view_mode_featured.yml
  config/sync/core.entity_view_display.node.custom_page.view_mode_tile.yml
  config/sync/core.entity_view_display.paragraph.simple_paragraph.default.yml
  config/sync/core.entity_view_display.paragraph.simple_paragraph.preview.yml
  config/sync/core.entity_view_mode.paragraph.preview.yml
  config/sync/core.extension.yml
  config/sync/field.field.message.collection_content_subscription.field_collection_content.yml
  config/sync/field.field.node.custom_page.field_paragraphs_body.yml
  config/sync/field.field.paragraph.simple_paragraph.field_body.yml
  config/sync/field.storage.node.field_paragraphs_body.yml
  config/sync/field.storage.paragraph.field_body.yml
  config/sync/paragraphs.paragraphs_type.simple_paragraph.yml
  config/sync/paragraphs.settings.yml
  config/sync/search_api.index.published.yml
  config/sync/search_api.index.unpublished.yml
  config/sync/views.view.group_feed.yml
  tests/behat-group-a-cphp.yml.dist
  tests/behat-group-b-cphp.yml.dist
  tests/behat-only-selenium-cphp.yml.dist
  tests/behat-remainder-cphp.yml.dist
  tests/behat.yml.dist
  tests/features/custom_page/community_content_listing.feature
  tests/features/paragraphs/custom_page.paragraphs.feature
  tests/features/report.feature
  tests/src/Traits/TabledragTrait.php
  tests/src/Traits/WysiwygTrait.php
  web/modules/custom/custom_page/config/optional/core.entity_form_display.node.custom_page.default.yml
  web/modules/custom/custom_page/config/optional/core.entity_view_display.node.custom_page.default.yml
  web/modules/custom/custom_page/config/optional/core.entity_view_display.node.custom_page.view_mode_featured.yml
  web/modules/custom/custom_page/config/optional/core.entity_view_display.node.custom_page.view_mode_tile.yml
  web/modules/custom/custom_page/custom_page.info.yml
  web/modules/custom/custom_page/custom_page.post_update.php
  web/modules/custom/custom_page/src/Plugin/search_api/processor/IncludeCustomPageContent.php
  web/modules/custom/joinup_communities/tallinn/tallinn.behat.inc
  web/modules/custom/joinup_event/joinup_event.module
  web/modules/custom/joinup_paragraphs/config/optional/core.entity_form_display.paragraph.simple_paragraph.default.yml
  web/modules/custom/joinup_paragraphs/config/optional/core.entity_view_display.paragraph.simple_paragraph.default.yml
  web/modules/custom/joinup_paragraphs/config/optional/field.field.paragraph.simple_paragraph.field_body.yml
  web/modules/custom/joinup_paragraphs/config/optional/field.storage.paragraph.field_body.yml
  web/modules/custom/joinup_paragraphs/config/optional/paragraphs.paragraphs_type.simple_paragraph.yml
  web/modules/custom/joinup_paragraphs/joinup_paragraphs.behat.inc
  web/modules/custom/joinup_paragraphs/joinup_paragraphs.info.yml
  web/modules/custom/joinup_search/config/install/search_api.index.published.yml
  web/profiles/joinup/joinup.behat.inc
  web/themes/joinup/templates/content/node--custom-page--full.html.twig
Labels: enhancement
