Repository ec-europa/joinup-dev, pull requests merged in 2020-04, with the labels that each got.

#2105 ISAICP-5970: Update dependencies
  composer.json
  composer.lock
Labels: ready for QA

#2104 ISAICP-5900: Strict assignment is required.
  web/modules/custom/asset_distribution/js/download_tracking.js
  web/themes/joinup/js/mdl-chips-input.js
Labels: ready for UAT

#2109 ISAICP-5972: Don't cache the redirect when a node changes its visibility
  composer.json
  composer.lock
  tests/features/eulogin/anonymous_403_redirect_caching.feature
Labels: high priority, ready for UAT

#2111 ISAICP-5978: SPARQL connection should be typed as interface
  web/modules/custom/joinup_core/src/RequirementsHelper.php
Labels: ready for QA
